[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
linker = "arm-none-eabi-gcc"
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tsrc/core/kernel.ld",
    "-Zlocation-detail=none",
    "-C",
    "link-arg=-mcpu=cortex-m7",
]
